소셜 로그인 구현 및 디자인 완료
TeamMatDai/cook-cook pull request #10
Opened 2024-07-11 21:31 UTC by taeyun01

미들웨어 진행중,,,

2024-07-12 04:26 UTC, 1eeyerin requested changes
전반적으로 context 및 zustand 관리에 어려움을 겪으셨을텐데 너무 고생이 많으셨습니다 태윤님!
다만 일부 코멘트 드리니 확인 부탁드립니다~

2024-07-12 04:26 UTC, 1eeyerin commented on next.config.mjs
> +      { hostname: "lh3.googleusercontent.com" },
이제는 없어도 되는 요소라고 생각됩니다.

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/(home)/page.tsx
> +  const { count, incrementCount, decrementCount } = useCounterStore((state) => state);
shallowEqual 을 통해서 리렌더링 및 상태값을 최적의 상태로 꺼내오는 것이 좋을 것 같다고 생각됩니다.
하지만 예제코드였네요..? 😵‍💫

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthContent.tsx
> +  const handleAuth = async (): Promise<void> => {
해당 코드가 Promise를 반환하고 있나요? 리턴문은 없는 것 같습니답

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthContent.tsx
> +    if (user) {
ealry return pattern을 사용하시면 가독성 있는 코드가 될 것으로 보입니다.

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthContent.tsx
> +        console.error(error);
해당 부분은 콘솔에만 띄워지는 부분이기 때문에 고객은 에러를 마주하게 되면 아무 변화도 예측할 수 없는 코드라고 생각됩니다.
에러 메세지를 alert로 명시적으로 전달해야 고객이 에러를 확인할 수 있습니다.

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +  const signInWithKakao = async ():Promise<void> => {
return의 패턴은 보이지 않는 것 같습니다.

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +      options: { redirectTo: `${process.env.NEXT_PUBLIC_BASE_URL}` }
해당 코드 팀내 전파가 되어야 하는 주소인 것 같습니다. 다른 분들의 env에는 해당 내용이 없어서요!

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +  const signInWithGoogle = async ():Promise<void> => {
이 역시 동일합니다

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +      <button
기본적으로 type=button을 명시할 수 있게 작성 부탁드립니다.

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +import { SupabaseClient, useSupabaseClient } from '@supabase/auth-helpers-react';
해당 컴포넌트 폴더 depth가 조금 어색한 것 같습니다. AuthContent 안에 존재해야하는 이유가 있을까요?

2024-07-12 04:26 UTC, 1eeyerin commented on src/app/(providers)/(root)/auth/page.tsx
> +    <div className="relative w-full h-dvh">
main 태그 사용하시면 적절한 시맨틱 태그가 부여될 것 같아요~

2024-07-12 04:26 UTC, 1eeyerin commented on src/icons/loginBackground.png
해당 파일은.. icon은 아닌 것 같습니당

2024-07-12 04:26 UTC, 1eeyerin commented on src/stores/counterStore.ts
> +export type CounterActions = {
음.. 테스트 코드..음..

2024-07-12 04:26 UTC, 1eeyerin commented on src/utils/supabase/middleware.ts
> +  // 미들웨어 수정중
나중에는 이런 일이 있다면 TODO 붙여주세요! TODO 찾아서 수월하게 제거할 수 있으나 현재 주석은 놓칠 가능성이 있습니다

2024-07-12 04:26 UTC, 1eeyerin commented on src/utils/supabase/middleware.ts
> +    url.pathname = '/auth';
제 생각에는 login이 더 적합할 것 같습니다. 애플리케이션 확장 가능성에서 본다면 auth는 추상적인 이름이 될 수 있습니다. 다른 auth 관련 페이지가 생성될 경우 어떤 페이지인지 의미를 희미해지게 만드는 것 같습니다.

2024-07-12 05:05 UTC, sorakim1130 approved these changes
확인 했습니다 user정보 드르와,,,!!고생많으셨네요 태윤님!!

2024-07-12 05:16 UTC, yeseul0809 approved these changes
확인완료했습니닷! 태윤님! 고생많으셨습니다-!!

2024-07-12 09:40 UTC, taeyun01 commented on next.config.mjs
> +      { hostname: "lh3.googleusercontent.com" },
외부 이미지를 사용하고 있어 설정 안해주면 에러가 납니다!

2024-07-12 09:41 UTC, taeyun01 commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthContent.tsx
> +  const handleAuth = async (): Promise<void> => {
너무 생각없이 작성했네요. 제거 했습니다!

2024-07-12 09:41 UTC, taeyun01 commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthContent.tsx
> +    if (user) {
넵 반영했습니다!

2024-07-12 09:41 UTC, taeyun01 commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthContent.tsx
> +        console.error(error);
반영했습니다!

2024-07-12 09:42 UTC, taeyun01 commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +  const signInWithKakao = async ():Promise<void> => {
제거 했습니다~!

2024-07-12 09:43 UTC, taeyun01 commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +      options: { redirectTo: `${process.env.NEXT_PUBLIC_BASE_URL}` }
넵 전달 하겠습니다~

2024-07-12 09:44 UTC, taeyun01 commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +  const signInWithGoogle = async ():Promise<void> => {
제거 했습니다~!

2024-07-12 09:44 UTC, taeyun01 commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +      <button
반영했습니다!

2024-07-12 09:47 UTC, taeyun01 commented on src/app/(providers)/(root)/auth/_components/AuthContent/AuthLogin.tsx
> +import { SupabaseClient, useSupabaseClient } from '@supabase/auth-helpers-react';
테스트 하려고 해둔건데 제거를 못했네요..
제거했습니다~!

2024-07-12 09:47 UTC, taeyun01 commented on src/app/(providers)/(root)/auth/page.tsx
> +    <div className="relative w-full h-dvh">
반영했습니다!

2024-07-12 09:48 UTC, taeyun01 commented on src/icons/loginBackground.png
public 폴더로 변경했습니다!

2024-07-12 09:48 UTC, taeyun01 commented on src/stores/counterStore.ts
> +export type CounterActions = {
테스트 코드 수정하겠습니다 ㅠㅠ

2024-07-12 10:03 UTC, taeyun01 commented on src/utils/supabase/middleware.ts
> +    url.pathname = '/auth';
넵 login페이지로 수정하였습니다!

2024-07-12 10:03 UTC, taeyun01 commented on src/utils/supabase/middleware.ts
> +  // 미들웨어 수정중
맞습니다.  // TODO로 변경했습니다!

2024-07-12 10:05 UTC, taeyun01 commented on src/app/(providers)/(root)/(home)/page.tsx
> +  const { count, incrementCount, decrementCount } = useCounterStore((state) => state);
넵.. 테스트 하려고 일단 해놨는데 빠르게 수정하겠습니다~

2024-07-12 15:22 UTC, 1eeyerin requested changes

2024-07-12 15:22 UTC, 1eeyerin commented on src/app/(providers)/(root)/login/page.tsx
> +import Background from '../../../../../public/loginBackground.png';
유지보수 관점에서 폴더 구조를 /public/images/login/ 위처럼 가져가는 것을 제안 드립니다.

2024-07-12 15:22 UTC, 1eeyerin commented on src/app/(providers)/(root)/login/page.tsx
> +import AuthLogin from '@/app/(providers)/(root)/login/_components/AuthLogin';
??????????

2024-07-12 15:22 UTC, 1eeyerin commented on src/app/(providers)/(root)/login/page.tsx
> +import CookcookLogo from '@/icons/cookcookLogo.svg';
컴포넌트 명으로도 유추 가능하도록 LogoIcon 이라는 이름으로 변경 제안드립니다 :)

2024-07-12 15:22 UTC, 1eeyerin commented on src/app/(providers)/(root)/login/_components/AuthLogin.tsx
> +  };
state를 사용하지 않는 함수를 함수 컴포넌트 안에 작성하게 된다면 리렌더링될 때마다 해당 함수를 재생성하게 됩니다..

2024-07-13 07:21 UTC, 1eeyerin approved these changes

2024-07-13 12:34 UTC, merged