상세페이지 개발 중간 코드리뷰 올립니다.
TeamMatDai/cook-cook pull request #12
Opened 2024-07-12 05:19 UTC by sorakim1130

아직 반영이 덜된 사항들이 많아 일단 TODO로 적어 두긴 했습니다.
북마크 컴포넌트 쪽 코드 주석은 무시해 주시면 감사하겠습니다. (아직 기능 구현이 불안정해서)
참고해주세요.

2024-07-12 12:06 UTC, 1eeyerin requested changes
코멘트 남깁니다! 소라님 고생 많으셨어요 :)

2024-07-12 12:06 UTC, 1eeyerin commented on package.json
> +    "supabase": ">=1.8.1",
소라님 혹시 이거 제거 가능하실까요? dev 디펜던시에 이미 있어서요!

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/[id]/page.tsx
> +import RecipeSection from '@/app/(providers)/(root)/detail/_components/RecipeSection';
import 경로에 오류가 있는 것 같습니다.
```suggestion
import RecipeSection from '@/app/detail/_components/RecipeSection';
```
혹시 이 경로로 안되실까요?

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/[id]/page.tsx
> +  const id = params?.id as string;
params에 타입 정의를 한다면 as로 단언하지 않아도 됩니다!

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/[id]/page.tsx
> +    queryKey: ['recipes'],
쿼리키에 아이디를 넣는다면, 해당 키 값으로 캐시 관리가 되어집니다!

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/[id]/page.tsx
> +          <Link href='/'>
prettier가 동작하지 않는 것 같습니다 소라님!

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/[id]/page.tsx
> +        style={{ backgroundImage: `url(${recipe?.thumbnail})`, backgroundSize: 'cover', backgroundPosition: 'center' }}
```
<div
  className="bg-cover bg-center"
  style={{ backgroundImage: `url(${recipe?.thumbnail})` }}
>
  {/* 콘텐츠 */}
</div>
```

이런 방식으로 image만 style 처리하는 것이 좋을 것 같습니다! (나머지 테일윈드 적용)

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/BookmarkButton.tsx
> +import { IconBookmark } from '@/icons/IconBookmark';
추후 추가되겠지만 tanstackQuery를 쓴다면 "use client"; 도 같이 사용 부탁드립니다.

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/BookmarkButton.tsx
> +      queryClient.setQueryData(['bookmark', recipesId, userId], true);
아하 제가 낙관적 업데이트 작성법을 스킵했지만 요게 그거군요..! 🎀

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/BookmarkButton.tsx
> +        queryClient.setQueryData(['bookmark', recipesId, userId], context.previousBookmark);
쿼리키를 2개나 이용하는 이유가 있울가요?!

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/BookmarkButton.tsx
> +    mutationFn: () => removeBookmark(recipesId, userId),
오 뭔가 하나로 합칠 수도 있을 것 같아요

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/BookmarkButton.tsx
> +    }
```suggestion
    if (isBookmarked) {
      removeBookmarkMutation.mutate();
      return;
    }
    addBookmarkMutation.mutate();
```

early return pattern 을 사용하실 것을 권장 드립니다

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/RecipeSection.tsx
> +            {recipe.time}분 · {recipe.level}
[HTML 엔티티(Entities) 정리](https://blog.outsider.ne.kr/380)
요고 `&middot;` 을 이용하여 충돌 방지를 하는 것을 제안드립니다!

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/ShareButton.tsx
> +  const handleShare = () => {
해당 코드를 보니 컴포넌트 아래에 있지 않아도 되는 함수로 보이며, 함수 컴포넌트 안에 둘 경우 렌더링이 될 때마다 재생성을 하기 때문에 함수 바깥에 두시는 것은 어떨까요?

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/ShareButton.tsx
> +          console.error('Error copying URL:', error);
안될 때도 고객에게 alert로 알려주세요!

2024-07-12 12:06 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/ShareButton.tsx
> +    <button className='rounded-lg w-[66px] h-[66px] flex flex-col gap-2 justify-center items-center border border-lightgray' onClick={handleShare}>
type="button" 명시 부탁드립니다~

2024-07-12 12:06 UTC, 1eeyerin commented on src/icons/IconShare.tsx
> +export const IconShare = () => (
오옴... 이거 직접 컴포넌트화 하는게 아니구 svg 파일 올리면 자동으로 컴포넌트로 사용하실 수 있어요!

2024-07-12 12:06 UTC, 1eeyerin commented on src/lib/fetchData.ts
해당 파일 src/services/recipes.ts  src/services/bookmark.ts 로 옮겨서 서비스단 로직을 한꺼번에 통일시키면 좋을 것 같습니다

2024-07-12 13:22 UTC, yeseul0809 reviewed
소라님 정말 고생많으셨어요! 👍
참고하시면 좋을것같은 코멘트 남겼습니다!!ㅎㅎ

2024-07-12 13:22 UTC, yeseul0809 commented on src/app/(providers)/(root)/detail/_components/ShareButton.tsx
> +          alert('URL이 클립보드에 복사되었습니다.');
alert 의 경우 swal 라이브러리 사용해보셨을까요?! 이미 알고계실것같은데 그래두 리뷰 남겨요! ㅎㅎ
방금 제가 src > utils 에 swal.ts 를 추가해놓았는데 나중에 merge 하고난후에 사용해보시는것도 추천드려욥!! 
사용법이 간단하면서 깔끔한 ui 더라구요~~~!! :-)

2024-07-12 13:22 UTC, yeseul0809 commented on src/icons/IconShare.tsx
> +export const IconShare = () => (
import PencilIcon from '@/icons/editor/pencil.svg';
import PhotoIcon from '@/icons/editor/photo.svg';

리액트와는 다르게 요렇게 바로 컴포넌트명 뽑아서 사용가능하더라구요!! 저도 이번에 배웠어요!

2024-07-12 13:22 UTC, yeseul0809 commented on yarn.lock
> +supabase@>=1.8.1:
애증의 supabase 버전.... 고생 많으셨씁니다 소라님!!

2024-07-12 13:22 UTC, yeseul0809 commented on src/app/(providers)/(root)/detail/_components/RecipeInstructionsSection.tsx
> +        dangerouslySetInnerHTML={{ __html: recipe.recipe }}
quill 사용하면서 알아보니까, 작성한 데이터 불러올때 dangerouslySetInnerHTML를 사용하게되는데 요게 XSS 공격에 취약할 수 있다고해요!
데이터를 안전하게 렌더링하려면 DOMPurify 를 사용하는게 좋을것같아서 라이브러리 설치는 해두었습니다!! 
```
const sanitizedRecipe = DOMPurify.sanitize(recipe.recipe);
     <div
        dangerouslySetInnerHTML={{ __html: sanitizedRecipe }}
        className="text-base text-gray-600 leading-1.5 mb-4"
      />
 ```
요렇게 수정가능하니 참고해주시면 감사하겠습니다-!! 😊

2024-07-12 14:55 UTC, taeyun01 approved these changes
소라님 고생하셨습니다~ 👍

2024-07-12 20:23 UTC, sorakim1130 commented on package.json
> +    "supabase": ">=1.8.1",
네! 지금 올라가있는 dev에 있는거지요??? 제거하겠습니다!

2024-07-12 20:23 UTC, sorakim1130 commented on src/app/(providers)/(root)/detail/[id]/page.tsx
> +import RecipeSection from '@/app/(providers)/(root)/detail/_components/RecipeSection';
음 네 저는 안되는데 ㅠㅠ 설정 문제일까요??

2024-07-12 20:23 UTC, sorakim1130 commented on src/app/(providers)/(root)/detail/[id]/page.tsx
> +  const id = params?.id as string;
오 네 감사합니다!! 수정했습니다

2024-07-12 20:23 UTC, sorakim1130 commented on src/app/(providers)/(root)/detail/_components/RecipeInstructionsSection.tsx
> +        dangerouslySetInnerHTML={{ __html: recipe.recipe }}
오! 감사합니다! dev 받고서 수정해야 할거 같네요 ㅠ

2024-07-12 20:23 UTC, sorakim1130 commented on src/app/(providers)/(root)/detail/_components/ShareButton.tsx
> +          alert('URL이 클립보드에 복사되었습니다.');
녜!! 예슬님 코드 받고서 사용하도록 하겠습니댜 감사햡니다~.~

2024-07-13 06:41 UTC, 1eeyerin requested changes

2024-07-13 06:41 UTC, 1eeyerin commented on next.config.mjs
> +        hostname: "**",
오..! 이거 안하면 반영 안되나여?!

2024-07-13 06:41 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/[id]/page.tsx
> +const DetailPage: React.FC = () => {
컴포넌트 리턴타입 통일 부탁드릴게요!

2024-07-13 06:41 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/BookmarkButton.tsx
> +const BookmarkButton: React.FC<BookmarkButtonProps> = ({ recipesId }) => {
해당 태그도 동일합니다!

2024-07-13 06:41 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/BookmarkButton.tsx
> +      console.error('@@REMOVE BOOKMARK ERROR:', err);
에러 있으면 고객에게 알려주는 것이 좋을 것 같아요!

2024-07-13 06:41 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/BookmarkButton.tsx
> +      if (context?.previousBookmark) {
early return pattern을 적용하면 좋을 것 같습니다!

2024-07-13 06:41 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/IngredientsSection.tsx
> +import React from 'react';
전체적으로 제거해도 될 것 같아요!

2024-07-13 06:41 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/IngredientsSection.tsx
> +const IngredientsSection: React.FC<{ materials: Recipe['material'] }> = ({ materials }) => (
전체적으로 컴포넌트 리턴타입 수정 부탁드립니다!

2024-07-13 06:41 UTC, 1eeyerin commented on src/app/(providers)/(root)/detail/_components/ShareButton.tsx
> +  } else {
동일합니다! early return pattern 부탁드립니다!

2024-07-13 06:41 UTC, 1eeyerin commented on src/services/recipesId.ts
레시피 코드들도 모아두면 좋을것 같아요!
`src/services/recipe.ts`

2024-07-13 07:21 UTC, 1eeyerin approved these changes

2024-07-13 09:25 UTC, sorakim1130 commented on next.config.mjs
> +        hostname: "**",
네 Next Image 컴포넌트 쓰면 이미지가 안나오더라구요!

2024-07-13 10:05 UTC, merged