작성하기 페이지 기능구현 관련 PR 입니다.
TeamMatDai/cook-cook pull request #6
Opened 2024-07-10 12:28 UTC by yeseul0809

- 디자인 작업 들어가기 전에 merge 한번 하는게 좋을것같아서 PR 올려요!

2024-07-10 14:25 UTC, 1eeyerin requested changes
예슬님 수고 많으셨습니다! 해당 부분 선택반영과, 수정이 필요한 부분 코멘트 드립니다~

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/CommonInput.tsx
> +import React from 'react';
타입만을 위해 사용하시는 것이라면, 가독성을 위해 앞에 type을 명시하는 것을 제안 드립니다~

https://velog.io/@hamjw0122/TS-import-type%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0#-import-type%EC%9C%BC%EB%A1%9C-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/CommonInput.tsx
> +      onChange={(e) => setValue(e.target.value)}
setValue 를 하위 컴포넌트에 내려주다 보면 effect가 어디까지 어떻게 영향을 미치는지 알지 못하는 단점이 있습니다. 
setValue가 선언된 컴포넌트에서 만든 onChange함수 자체를 내려주면 데이터가 어떠한 변경이 일어나는지 한 컴포넌트에서 관심사가 한눈에 보이는 장점이 있습니다!
단지 제안이니 고려하지 않으셔도 됩니다.

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/FileInput.tsx
> +    <input type="file" onChange={onChange} ref={ref} className="hidden" />
일부 필드는 ref를 사용하고, 다른 일부 필드는 useState를 사용하신 이유가 있을까요?

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/LevelSelector.tsx
> +  level: string;
회의시 논의하기로는 
```
 “easy” | ”medium” | “hard”
```
의 union 타입으로 주기로 했던 것 같은데 혹시 의사결정이 변경 된 이유가 있을까요?

또한 현재같이 값이 3개 중 하나로 반드시 오는 경우라면 union 타입으로 타입을 더 명확하게 주는 것을 제안 드립니다~

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/LevelSelector.tsx
> +    <div>
해당 div는 혹시 반드시 존재해야하는 div일까요?

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/LevelSelector.tsx
> +      <p>난이도</p>
문장이 아니니 strong이나 div 태그 또는 더 시맨틱한 다른 태그가 있을 것으로 보입니다~

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/LevelSelector.tsx
> +      <button
기본적인 타입은 submit이기 때문에 type="button"으로 submit이 되지 않는다는 것을 명시적으로 주는 것을 제안드립니다~

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/LevelSelector.tsx
> +        style={{ backgroundColor: level === '상' ? 'gray' : 'white' }}
tailwind를 공통 컨벤션으로 사용하고 있는 것으로 알고 있는데 예외를 두시는 이유가 있으실까요?

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/MaterialList.tsx
> +    setMaterial([...material, { name: '', value: '' }]);
prev 사용으로 setState의 배치업데이트의 위험성을 방지할 수 있는 좋은 코드를 만들 수 있습니다 :)

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/MaterialList.tsx
> +    if (material.length > 1) {
early return pattern으로 가독성 있는 코드를 만들 수 있습니다 :)
https://woonys.tistory.com/209

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/MaterialList.tsx
> +    <div>
반드시 사용해야하는 div인지 궁금합니다~

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/MaterialList.tsx
> +      <p>기본재료</p>
동일합니다

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/MaterialList.tsx
> +          <input
혹시 해당 코드는 CommonInput 를 사용하지 않는 이유가 있으실까요?
컴포넌트명만 보고 행동을 유추했을때 모든 input 태그를 대체할 수 있을 것으로 보여져서 여쭤봅니다!

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/QuillEditor.tsx
> +    const { default: RQ } = await import('react-quill');
코드를 대충봐도 이해할 수 있도록 이름을 명시적으로 작성해주시면 좋을 것 같습니다~

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/QuillEditor.tsx
> +    return function Quill({ forwardedRef, ...props }: ForwardedQuillComponent) {
화살표함수를 사용하시다가 해당 코드에서만 선언형 컴포넌트를 사용하신 이유가 있을까요?
this를 사용하는 것도 아닌 것 같아서 문의드립니다!

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/QuillEditor.tsx
> +  console.log('에디터에서 이미지버튼 클릭');
console은 제거 부탁드립니다~

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/QuillEditor.tsx
> +  input.click();
아.. 제가 퀼로 구현해본적이 없지만 퀼은.. 이렇게 돔을 생성해서 클릭을 트리거 하는군요 ㅠㅠ 🥲

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/QuillEditor.tsx
> +        console.log('이미지가 성공적으로 업로드되었습니다:', data);
console로 성공을 알리는 이유가 있을까요?

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/QuillEditor.tsx
> +        } else {
전체적으로 if else문이 반복되어 가독성이 해치는 것 같습니다!
early return pattern을 제안 드립니다

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/QuillEditor.tsx
> +const QuillEditor: React.FC<QuillEditorProps> = ({ value, setValue }) => {
컴포넌트가 너무 헤비해서 나중에는 컴포넌트 분리도 생각해보시면 좋을 것 같습니다~

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/QuillEditor.tsx
> +  const formats = [
상수를 컴포넌트 안에 작성하시면, 렌더링할때마다 계속 생성하게 되므로 컴포넌트 바깥으로 이동 부탁드립니다~

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/_components/TimeInput.tsx
> +  <div>
동일합니다

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +    } else {
동일합니다

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +      }
동일합니다..

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +      setLevel('쉬움');
이렇게 전체 state가 동시에 처리되어야하는 정도라면.. state를 하나로 묶는 것도 고려해볼 수 있으나, 몇개는 useState 없이 useRef만으로도 구현 가능한 필드가 있을 것이라 생각됩니다.
많은 state는 리렌더링을 촉구하여 컴포넌트의 성능을 떨어트릴 수 있습니다.

2024-07-10 14:25 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +    <div>
동일합니다

2024-07-10 14:25 UTC, 1eeyerin requested changes
예슬님 수고 많으셨습니다! 해당 부분 선택반영과, 수정이 필요한 부분 코멘트 드립니다~

2024-07-10 17:19 UTC, sorakim1130 approved these changes
예슬님 너무 고생 많으셨습니다 ! 궁금했던 부분 예린님께서 코멘트 남겨주셔서 저는 승인 눌러 놓겠습니다!

2024-07-10 18:22 UTC, yeseul0809 commented on src/app/editor/_components/LevelSelector.tsx
> +    <div>
해당부분 fragment로 수정했습니다.

2024-07-10 18:25 UTC, yeseul0809 commented on src/app/editor/_components/LevelSelector.tsx
> +      <p>난이도</p>
각각 fragment와 h4로 수정했습니다.

2024-07-10 18:26 UTC, yeseul0809 commented on src/app/editor/_components/LevelSelector.tsx
> +      <button
type="button" 으로 수정했습니다.

2024-07-11 06:37 UTC, 1eeyerin commented on src/app/editor/_components/LevelSelector.tsx
> +      <p>난이도</p>
혹시 이 페이지 위에는 h1, h2, h3가 존재하는 것일까요? 유지보수 관점에서 꼭 필요한 depth인지 궁금합니다!

2024-07-11 07:06 UTC, 1eeyerin requested changes
수정 완료시 코멘트를 꼭 달아주세요! 어디까지 수정되었는지 파악이 어려운 부분이 있슘니댜!

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/Header.tsx
> +    <button>
요기도 type 추가 부탁두림니댜

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/Header.tsx
> +import BackIcon from '../../../icons/editor/back.svg';
혹시 상대경로로 써야하는 이유가 있을까요?

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/Header.tsx
> +import React from 'react';
필요없다면 제거 부탁드립니다!

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/Header.tsx
> +    <p>글쓰기</p>
아마 이게 heading 태그를 넣기 적합해 보입니다! 아니면 strong 태그 부탁드려요!

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/LevelSelector.tsx
> +  const levelMap: { [key in Level]: string } = {
해당 코드는 컴포넌트 바깥에 있어도 될 것 같습니다.
함수 리렌더링시 계속 재생성하는데 렌더링시마다 생성되어야하는 값은 아닌 것으로 보입니다!
참고로 변하지 않는 상수라면 대문자 규칙을 따르시면 좋을 것 같습니다.

```
levelMap > LEVEL_MAP
```

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/LevelSelector.tsx
> +          const currentLevel = key as Level;
as로 단언해야하는 이유가 있을까요?
단언은 타입이 예상대로 잘 먹히지 않았을 때 주로 사용합니다.

as를 써야할 일이 정말 어쩔 수 없을 경우에만 쓰는 것을 추천드리며, 만약 그런 오류가 생긴다면 위에 타입 지정에 문제가 있을 것으로 보입니다.

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/LevelSelector.tsx
> +              }`}
단순 제안이지만 나중에 리팩터링 하실때는 cva를 써보시는 것도 추천드립니다~
복잡한 className 정의를 명시적으로 선언할 수 있도록 도와주는 라이브러리이며, 현재 프로젝트에서도 설치되어있습니다!


https://github.com/TeamMatDai/cook-cook/blob/b9be5528d3ac379c8107a28585b061e2210f41fb/src/app/(providers)/(root)/mypage/recipe/page.tsx#L34

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/MaterialList.tsx
>  import React from 'react';
여기도 수정 부탁드립니다!

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/MaterialList.tsx
> +      <h4 className="w-[60px] h-[18px] font-semibold mt-7 mb-4">기본재료</h4>
동일합니다

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/MaterialList.tsx
> +            setValue={(value) => handleMaterialChange(index, 'name', value)}
갯수가 많아지면, 인자값이 바뀔 우려가 있으므로 객체로 넣어주는 것을 제안드립니다.

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_components/QuillEditor.tsx
>      []
이거 디펜던시 에러 안 나나요?!
quillRef 가 들어가야할 것 같아서 말씀드립니다!
일단 에러 안 나면 해당 코멘트는 무시 부탁드려요~

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_utils/handleSubmit.ts
> +  setState(() => initialState);
혹시 여기서 초기값으로 변경해야하는 이유가 있을까요?
prev를 사용하지 않는다면 콜백함수를 이용할 필요가 없다고 생각됩니다!

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/_utils/handleSubmit.ts
> +    fileInputRef.current.value = '';
혹시 여기서 초기값으로 변경해야하는 이유가 있을까요? 이 역시 동일합니다!

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +}
제가 전체적인 코드베이스를 몰라서 그러는데 재활용 가능한 타입이라면 type.ts를 따로 분리해서 export하는 것이 좋을 것 같습니다. 그러면 해당 페이지 내에서 재활용되는 타입을 컴포넌트 파일을 일일히 다 보지 않더라도 쉽게 파악할 수 있습니다.

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +export const initialState: State = {
대문자로 상수임을 명확하게 나타내주세요!

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +const EditPage: React.FC = () => {
혹시 추론이 가능한데 FC임을 명시하시는 이유가 있으실까요?

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +      ...state,
해당 패턴도 prev => 로 변경하는 것을 추천 드립니다.

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +  const handleChange = (key: keyof State, value: any) => {
왜.. any 일까요?

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +      ...state,
동일합니다

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/page.tsx
> +      <Header onSubmit={() => handleSubmit(state, setState, fileInputRef)} />
이 역시 인자값이 뒤바뀌어 에러가 나는 경우를 막을 수 있는 객체 형식으로 인자를 제공하면 좋을 것 같습니다.

2024-07-11 07:06 UTC, 1eeyerin commented on src/app/editor/page.tsx
>          {/* quill 에디터 하단여백 */}
주석은 필요 없을 것으로 보입니다~

2024-07-11 07:24 UTC, yeseul0809 commented on src/app/editor/_components/Header.tsx
> +    <button>
타입추가했습니다.

2024-07-11 07:27 UTC, yeseul0809 commented on src/app/editor/_components/Header.tsx
> +import BackIcon from '../../../icons/editor/back.svg';
익숙한게 상대경로이다보니 자연스럽게 사용했네요! 절대경로로 수정완료했습니다.

2024-07-11 07:27 UTC, yeseul0809 commented on src/app/editor/_components/Header.tsx
> +import React from 'react';
제거완료했습니다.

2024-07-11 07:34 UTC, yeseul0809 commented on src/app/editor/_components/Header.tsx
> +    <p>글쓰기</p>
strong 태그로 수정했숩니다.

2024-07-11 07:52 UTC, yeseul0809 commented on src/app/editor/_components/LevelSelector.tsx
> +  const levelMap: { [key in Level]: string } = {
변수명 수정 후 constants.ts 상수 파일로 분리시켰습니다.

2024-07-11 08:11 UTC, yeseul0809 commented on src/app/editor/_components/LevelSelector.tsx
> +          const currentLevel = key as Level;
타입수정 후 as 제거했습니다.

2024-07-11 08:18 UTC, yeseul0809 commented on src/app/editor/_components/LevelSelector.tsx
> +              }`}
리팩토링시 사용해보겠습니다!

2024-07-11 08:18 UTC, yeseul0809 commented on src/app/editor/_components/MaterialList.tsx
>  import React from 'react';
수정완료했습니다.

2024-07-11 08:19 UTC, yeseul0809 commented on src/app/editor/_components/MaterialList.tsx
> +      <h4 className="w-[60px] h-[18px] font-semibold mt-7 mb-4">기본재료</h4>
strong 태그로 변경했습니다

2024-07-11 08:53 UTC, yeseul0809 commented on src/app/editor/_components/CommonInput.tsx
> +import React from 'react';
수정했씁니다

2024-07-11 10:42 UTC, yeseul0809 commented on src/app/editor/_components/QuillEditor.tsx
>      []
네네 해당부분 에러 없습니다!

2024-07-11 12:32 UTC, yeseul0809 commented on src/app/editor/page.tsx
>          {/* quill 에디터 하단여백 */}
넵 지웠습니다!

2024-07-11 14:33 UTC, yeseul0809 commented on src/app/editor/_components/LevelSelector.tsx
> +      <p>난이도</p>
strong 태그로 수정했습니다.

2024-07-11 14:34 UTC, yeseul0809 commented on src/app/editor/_components/LevelSelector.tsx
> +  level: string;
타입부분 수정완료했습니다.

2024-07-11 14:36 UTC, yeseul0809 commented on src/app/editor/_utils/handleSubmit.ts
> +    fileInputRef.current.value = '';
네 초기값으로 변경안하면 작성후에 input 칸에 여전히 이전에 입력한 값이 남아있어서요!

2024-07-11 15:06 UTC, yeseul0809 commented on src/app/editor/_utils/handleSubmit.ts
> +  setState(() => initialState);
아래의 이유와 같습니다! 콜백함수 수정했습니다.

2024-07-11 15:14 UTC, yeseul0809 commented on src/app/editor/page.tsx
> +}
네 분리했습니다~!

2024-07-11 15:16 UTC, yeseul0809 commented on src/app/editor/page.tsx
> +export const initialState: State = {
수정했습니다!

2024-07-11 15:17 UTC, yeseul0809 commented on src/app/editor/page.tsx
> +const EditPage: React.FC = () => {
다른 컴포넌트에서 children 을 내려주다보니 습관적으로 작성했네요 ㅜ 수정했습니다!

2024-07-11 15:20 UTC, yeseul0809 commented on src/app/editor/page.tsx
> +      ...state,
네 수정했습니다!

2024-07-11 15:43 UTC, yeseul0809 commented on src/app/editor/page.tsx
> +  const handleChange = (key: keyof State, value: any) => {
value 에 여러타입이 들어가서 우선 any 로 지정해놨었어요!
제네릭으로 수정했습니다!

2024-07-11 15:44 UTC, yeseul0809 commented on src/app/editor/page.tsx
> +      ...state,
수정했습니다.

2024-07-11 15:52 UTC, yeseul0809 commented on src/app/editor/page.tsx
> +      <Header onSubmit={() => handleSubmit(state, setState, fileInputRef)} />
네 수정했씁니다!

2024-07-11 15:59 UTC, yeseul0809 commented on src/app/editor/_components/MaterialList.tsx
> +            setValue={(value) => handleMaterialChange(index, 'name', value)}
수정했습니다!

2024-07-11 16:07 UTC, yeseul0809 commented on src/app/editor/_components/QuillEditor.tsx
> +    return function Quill({ forwardedRef, ...props }: ForwardedQuillComponent) {
이부분 로직이 어렵다보니 return 이 명시되어있는게 이해하기 쉽더라구요.. 다시 보니 일관성있게 화살표함수를 사용하는게 좋을거같아요! 수정했습니다~!!

2024-07-11 16:43 UTC, yeseul0809 commented on src/app/editor/_components/FileInput.tsx
> +    <input type="file" onChange={onChange} ref={ref} className="hidden" />
파일입력은 썸네일 선택할때 DOM 요소를 참조하므로 useRef 사용하는게 나을거같다고 생각했습니다 -!

2024-07-11 17:12 UTC, yeseul0809 commented on src/app/editor/_components/CommonInput.tsx
> +      onChange={(e) => setValue(e.target.value)}
네! 감사합니다
다음에 참고해서 리팩토링 해보겠습니다-!!

2024-07-12 04:01 UTC, 1eeyerin requested changes

2024-07-12 04:01 UTC, 1eeyerin commented on tsconfig.json
> +      "@icons/*": ["./src/icons/*"]
해당 코드를 alias로 설정하신 이유가 있을까요? 공통 룰이라 팀원에게 전파가 되어야하는 요소 같습니다.

2024-07-12 04:29 UTC, yeseul0809 commented on tsconfig.json
> +      "@icons/*": ["./src/icons/*"]
[9bcb7a1](https://github.com/TeamMatDai/cook-cook/pull/6/commits/9bcb7a1120b394337d3e3dc07e02c3f926f72bb8)

ㅠㅜ 알아보면서 하다가 헷갈렸어요! 수정했습니다!!

2024-07-12 04:44 UTC, 1eeyerin requested changes

2024-07-12 04:44 UTC, 1eeyerin commented on src/app/(providers)/(root)/editor/_components/Header.tsx
> +      <button>
a태그와 button태그는 중첩이 될 수 없습니다!
의미가 전혀 달라서요!

"/" 페이지로 이동한다는 내용은, 브라우저의 히스토리를 추가하는 것이기 때문에 의도와 다르게 사용이 된다고 생각합니다!

```
"use client";
import { useRouter } from "next/navigation";
const router = useRouter();
```
최신 버전은 주소가 이렇다고 하니 참고 부탁드려요!

useRouter의 router.back()을 이용하시면 히스토리 스택을 제거하며 뒤로가는 역할을 수행하게 됩니다!


혹시 해당 내용 조금 어려우시면 언제든지 디엠 부탁드립니다! 구두로 설명두 가눙합니댜 !! 🍀

2024-07-12 04:45 UTC, 1eeyerin requested changes

2024-07-12 04:45 UTC, 1eeyerin commented on src/app/(providers)/(root)/editor/_components/Header.tsx
>  import BackIcon from '@icons/editor/back.svg';
alias가 제거되었으니 @/icons/ 가 맞을 것 같습니다!

2024-07-12 05:08 UTC, yeseul0809 commented on src/app/(providers)/(root)/editor/_components/Header.tsx
> +      <button>
앗 그렇군요~~!! 새로 알아갑니다!! 수정했어요!

2024-07-12 05:10 UTC, yeseul0809 commented on src/app/(providers)/(root)/editor/_components/Header.tsx
>  import BackIcon from '@icons/editor/back.svg';
넵 수정완료했씁니다!

2024-07-12 05:25 UTC, 1eeyerin approved these changes
예슬님! 리뷰의 양이 방대해서 어려움이 많으셨을 것으로 생각됩니다! 
전체적으로 빠른 호흡으로 빠르게 반영해주셔서 너무 감사합니다 🥹💜👍🏻👍🏻👍🏻👼🏻🤍

다만 전체적으로 변경점이 많아 한번 전체적인 기능 동작 테스트 후 병합 부탁드리겠습니다! 정말 수고 많으셨습니다!! 🍀

2024-07-12 06:43 UTC, yeseul0809 commented
넵!  병합하겠습니다~~! 예린님도 고생많으셨습니다.. ㅠㅠ!! 
감사합니다 :-)

2024-07-12 06:43 UTC, merged